### ISSUE TITLE
Add unique level names (if available) to cubes endpoint

### ISSUE THREAD

**Issue by MarcioPorto** [tesseract-olap/tesseract#168]

**Comment by hwchen** [comment]
@MarcioPorto @frabarz since unique names resolution is actually part of logic layer, I'd actually expect there to be a separate logic layer endpoint for metadata. What do you think?

I think the other solution might be to keep the same metadata endpoint, but mark unique names as being resolved from logic layer. There could be a variety of formats, but I think it's good to separate logic layer enabled features somehow.

**Comment by frabarz** [comment]
What other fields would be needed for logiclayer queries in this case?
I think having a unique name field would be useful for the normal /cubes endpoint, because it acts as a shorter cube-wide id for the level.
Also, the rewrite I did for olap-client is prepared to use a more agnostic query object and [use it in both](https://github.com/Datawheel/olap-client/blob/master/src/tesseract/datasource.ts#L59-L67) "aggregate" and "logiclayer" endpoints. I could make it do some more requests in the middle though, since the response is async anyway.

**Comment by MarcioPorto** [comment]
I don't mind having a separate logic layer metadata endpoint, but I don't like that basically the only difference between the two endpoints would be the presence of the unique names in the response. So I don't think we gain much from splitting them up in this case. 

If we end up needing more detailed metadata information for the logic layer in the future, I think it would make more sense to have 2 endpoints. But for now, I would prefer a single shared endpoint.
